### ISSUE TITLE
Pie chart not updating data

### ISSUE THREAD

**Issue by juanpasolano** [projectweekend/angular-peity#2]
Hi. Thanks for the project.

I am trying to make a pie-chart but the data does not get updated when it changes. See plunkr for demo
https://plnkr.co/edit/7rtX5mfDQYw8B2UFxbE2

**Comment by juanpasolano** [comment]
I found a fix 
https://plnkr.co/edit/3R8WpO7A8PEgCdAS7LlU

I could make a pull-request if you are still maintaining the project.

**Comment by projectweekend** [comment]
Thanks for opening the issue. PRs are welcome. I haven't used this in a while, but I'm happy to keep it updated.
