### ISSUE TITLE
Watcher didn't work on array

### ISSUE THREAD

**Issue by JetMuffin** [projectweekend/angular-peity#5]
Hello,
I'm trying to use the line-chart to make a monitor for cpu usage but the data didn't get updated when it changed.

I found that the watcher works when I update some elements of an array, but doesn't work when push or shift to the array.

I checked the source code and found  that at [line 39-41](https://github.com/projectweekend/angular-peity/blob/master/angular-peity.js#L39) 
```javascript
      var watcher = scope.$watch('data', function(){
        span.textContent = scope.data.join();
        jQuery( span ).change();
      });
```
The watcher doesn't have params `objectEquality`. So I changed it to 

```javascript
      var watcher = scope.$watch('data', function(){
        span.textContent = scope.data.join();
        jQuery( span ).change();
      }, true);
```
And it works,  maybe the `objectEquality` params should be added to the watcher?

**Comment by projectweekend** [comment]
Thanks for opening the issue. I appreciate the feedback. I'm out of town for a few days. Feel free to open a pull request with the proposed fix.
